
package gov.nist.healthcare.hl7ws.messagevalidation;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import hl7ws.healthcare.nist.gov.validation.message.MessageValidationV2;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-05-18T13:45:55.747-04:00
 * Generated source version: 3.0.5
 * 
 */
public final class MessageValidationV2Interface_MessageValidationV2ServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://gov.nist.healthcare.hl7ws/validation/message", "MessageValidationV2");

    private MessageValidationV2Interface_MessageValidationV2ServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MessageValidationV2.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MessageValidationV2 ss = new MessageValidationV2(wsdlURL, SERVICE_NAME);
        MessageValidationV2Interface port = ss.getMessageValidationV2ServicePort();  
        
        {
        System.out.println("Invoking loadResource...");
        java.lang.String _loadResource_arg0 = "_loadResource_arg01947341590";
        java.lang.String _loadResource_arg1 = "_loadResource_arg1407722734";
        java.lang.String _loadResource_arg2 = "_loadResource_arg21633380549";
        java.lang.String _loadResource__return = port.loadResource(_loadResource_arg0, _loadResource_arg1, _loadResource_arg2);
        System.out.println("loadResource.result=" + _loadResource__return);


        }
        {
        System.out.println("Invoking validate...");
        java.lang.String _validate_arg0 = "_validate_arg01909106204";
        java.lang.String _validate_arg1 = "_validate_arg1-2115084867";
        java.lang.String _validate_arg2 = "_validate_arg2328371247";
        java.lang.String _validate_arg3 = "_validate_arg3-1624909613";
        java.lang.String _validate__return = port.validate(_validate_arg0, _validate_arg1, _validate_arg2, _validate_arg3);
        System.out.println("validate.result=" + _validate__return);


        }
        {
        System.out.println("Invoking getServiceStatus...");
        java.lang.String _getServiceStatus__return = port.getServiceStatus();
        System.out.println("getServiceStatus.result=" + _getServiceStatus__return);


        }

        System.exit(0);
    }

}
