
package gov.nist.healthcare.hl7ws.messagevalidation;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import hl7ws.healthcare.nist.gov.validation.message.MessageValidationV2;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2016-03-29T10:23:11.699-04:00
 * Generated source version: 3.0.5
 * 
 */
public final class MessageValidationV2Interface_MessageValidationV2ServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://gov.nist.healthcare.hl7ws/validation/message", "MessageValidationV2");

    private MessageValidationV2Interface_MessageValidationV2ServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MessageValidationV2.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MessageValidationV2 ss = new MessageValidationV2(wsdlURL, SERVICE_NAME);
        MessageValidationV2Interface port = ss.getMessageValidationV2ServicePort();  
        
        {
        System.out.println("Invoking loadResource...");
        java.lang.String _loadResource_arg0 = "_loadResource_arg0-1073817247";
        java.lang.String _loadResource_arg1 = "_loadResource_arg1-1225326720";
        java.lang.String _loadResource_arg2 = "_loadResource_arg2679332724";
        java.lang.String _loadResource__return = port.loadResource(_loadResource_arg0, _loadResource_arg1, _loadResource_arg2);
        System.out.println("loadResource.result=" + _loadResource__return);


        }
        {
        System.out.println("Invoking validateDQA...");
        java.lang.String _validateDQA_arg0 = "_validateDQA_arg0-601312852";
        java.lang.String _validateDQA_arg1 = "_validateDQA_arg1-868951571";
        java.lang.String _validateDQA_arg2 = "_validateDQA_arg21383128325";
        java.lang.String _validateDQA_arg3 = "_validateDQA_arg3-1053176408";
        java.lang.String _validateDQA_arg4 = "_validateDQA_arg4-787423221";
        java.lang.String _validateDQA__return = port.validateDQA(_validateDQA_arg0, _validateDQA_arg1, _validateDQA_arg2, _validateDQA_arg3, _validateDQA_arg4);
        System.out.println("validateDQA.result=" + _validateDQA__return);


        }
        {
        System.out.println("Invoking validate...");
        java.lang.String _validate_arg0 = "_validate_arg025807211";
        java.lang.String _validate_arg1 = "_validate_arg11817114187";
        java.lang.String _validate_arg2 = "_validate_arg2470055341";
        java.lang.String _validate_arg3 = "_validate_arg3-156764443";
        java.lang.String _validate__return = port.validate(_validate_arg0, _validate_arg1, _validate_arg2, _validate_arg3);
        System.out.println("validate.result=" + _validate__return);


        }
        {
        System.out.println("Invoking getServiceStatus...");
        java.lang.String _getServiceStatus__return = port.getServiceStatus();
        System.out.println("getServiceStatus.result=" + _getServiceStatus__return);


        }

        System.exit(0);
    }

}
